// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmwM8Hm_gEbYIkw145F-Wq-Q0KCeo3-C4',
    appId: '1:492068212750:android:918f3203d9df4e48852c5f',
    databaseURL: 'https://clockwrk-a6ea2-default-rtdb.europe-west1.firebasedatabase.app',
    messagingSenderId: '492068212750',
    projectId: 'clockwrk-a6ea2',
    storageBucket: 'clockwrk-a6ea2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa_gZYKoKKbNxPsRV47wfbLac6G-rpb3A',
    appId: '1:492068212750:ios:6a0f0783cb087494852c5f',
    databaseURL: 'https://clockwrk-a6ea2-default-rtdb.europe-west1.firebasedatabase.app',
    messagingSenderId: '492068212750',
    projectId: 'clockwrk-a6ea2',
    storageBucket: 'clockwrk-a6ea2.appspot.com',
    iosBundleId: 'com.clockwrk.clockwrkLogin',
  );
}
